name: App Build

on: pull_request

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Run Linter
        run: ./gradlew ktlintCheck

      - name: Build Project
        run: ./gradlew assemble

      - name: Run Tests
        run: ./gradlew test

  smoke-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Set up emulator and run smoke test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew -Pandroid.testInstrumentationRunnerArguments.class=com.example.pulmonaryrehabilitation.activity.splash.LoginActivitySmokeTest connectedAndroidTest